name: Build
on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**.md'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm ci
      # - run: npm run lint
      - run: npm run build
      - run: npm run test-ci
